default_platform(:ios)

platform :ios do

  desc "Build iOS app"
  lane :build do
    sh("flutter clean")
    sh("flutter pub get")
    sh("flutter build ios --release")
  end

  desc "Upload build to TestFlight"
  lane :internal do
    build

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner"
    )

    upload_to_testflight
  end

  desc "Upload to App Store production"
  lane :production do
    version_line = File.readlines("../../pubspec.yaml").find { |l| l.start_with?("version:") }
    build_number = version_line.split("+")[1].strip

    UI.message("Releasing iOS build #{build_number}")

    upload_to_app_store(
      submit_for_review: true,
      automatic_release: true,
      build_number: build_number
    )
  end

end