default_platform(:android)

platform :android do

  desc "Run tests"
  lane :test do
    sh("flutter test")
  end

  desc "Build Flutter App Bundle"
  lane :build do
    sh("flutter clean")
    sh("flutter pub get")
    sh("flutter build appbundle --release")
  end

  desc "Deploy to Play Store INTERNAL"
  lane :internal do
    build

    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      mapping: "../build/app/outputs/mapping/release/mapping.txt"
    )
  end

  desc "Deploy to Play Store PRODUCTION"
  lane :production do
    version_line = File.readlines("../../pubspec.yaml").find { |l| l.start_with?("version:") }
    version_code = version_line.split("+")[1].strip.to_i

    UI.message("Promoting versionCode #{version_code}")

    upload_to_play_store(
      track: "internal",
      version_code: version_code,
      track_promote_to: "production",
      track_promote_release_status: "completed"
    )
  end

end